### PR TITLE
Fixes #43: Players Position Changer Bug Fix

### LINKED ISSUE #43: PlayerPosition::Changer Bug
Bugs on when a player suddenly joins a game

#### Expected:
- Correct positioning

#### Actual:
- incorrect positioning

### PR DESCRIPTION
**Pull request by jnsoo123**
- changed logic of `PlayerPosition::Changer`
- updated specs
- added position saver in `PlayerHistorySaver`

### CODE REVIEW

File: app/services/player_position/changer.rb [hunk 1]
```diff
@@ -4,6 +4,11 @@ def initialize(lobby)
       @lobby      = lobby
       @game_count = lobby.games.count
       @players    = lobby.seated_players.order(:seat_number)
+      @last_game  = if @lobby.games.last(2).first == @lobby.games.last
```
Comment (gxaAlfie) [inline app/services/player_position/changer.rb]: you could use `second_to_last` method here instead of `last(2).first`

File: app/services/player_position/changer.rb [hunk 2]
```diff
@@ -4,6 +4,11 @@ def initialize(lobby)
...
+                      nil
+                    else
+                      @lobby.games.last(2).first
```
Comment (gxaAlfie) [inline app/services/player_position/changer.rb]: Also here

File: app/services/player_position/changer.rb (hunk 1 above)
Comment (gxaAlfie) [reply app/services/player_position/changer.rb]: > ~you could use `second_to_last` method here instead of `last(2).first`~

actually nevermind, this may possibly change the meaning of the code in the case where there is only one `Game` record since `last(2).first` will still return one item but `second_to_last` will return `nil`

File: app/services/player_position/changer.rb (hunk 2 above)
Comment (gxaAlfie) [reply app/services/player_position/changer.rb]: > ~also here~

actually nevermind, this may possibly change the meaning of the code in the case where there is only one Game record since last(2).first will still return one item but second_to_last will return nil

File: app/services/player_history_saver.rb [hunk 3]
```diff
@@ -18,7 +18,8 @@ def save_player_history
       PlayerHistory.create(
         player: player,
         game: @game,
-        seat_number: player.seat_number
+        seat_number: player.seat_number,
+        position: player.position
```
Comment (gxaAlfie) [inline app/services/player_history_saver.rb]: @jnsoo123 do we still need the `set_position` callback method in `player_history` after adding this?

Comment (jnsoo123) [reply app/services/player_history_saver.rb]: not sure what file youre talking about. gonna merge this
